# Generated by Django 3.2.6 on 2022-11-22 11:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_alter_comment_ticketlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketlist',
            name='like_users',
            field=models.ManyToManyField(related_name='like_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
